name: build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: printenv
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: browser-actions/setup-chrome@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: "Run tests"
        run: |
          pytest
